### PR TITLE
feat: project section

### PR DESCRIPTION
**Pull request by SirEctor**
What do you guys think of this updated project section. I know we wanted to merge all the sections together today, but I'm guessing since we're all on the same page, it might end up working (or not) if we merge one after another. So I'm just going to submit this request, and you can tell me if this will work with all of our sections together.

### CODE REVIEW

**Comment by LindaNayeli104** [comment]
They are very good contributions! All of them work.
It will be great If you use the tag "section" to divide the app and make it easier to merge.

**Comment by SirEctor** [comment]
@LindaNayeli104  You're absolutely right! I'll be right on that! Section tag with an id "project-section" would be good?

**Comment by aHappyCamer** [comment]
I agree with @LindaNayeli104 about the section. Other than that everything seems fine but a heads up I will be adding a main.js for us to add functionality

**Comment by LindaNayeli104** [comment]
> 
> 
> @LindaNayeli104 You're absolutely right! I'll be right on that! Section tag with an id "project-section" would be good?

Perfect!

**Review by LindaNayeli104 — APPROVED** [review]

**Pull request merged**
